# Change these first
owner: OmkarPatil2510 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
user-agent: OmkarPatil2510

sites:
  - name: Neosisly Production
    url: https://neosisly-326827350820.asia-south1.run.app/up

status-website:
  # Since you are using OmkarPatil2510.github.io/uptime, you MUST uncomment baseUrl
  baseUrl: /uptime 
  name: Neosisly Status
  introTitle: "Neosisly Uptime Monitor"
  introMessage: "Real-time monitoring for the Neosisly Rails 8 production environment."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/OmkarPatil2510/uptime

# This ensures the bot can open issues if the site goes down
# assignees:
#   - OmkarPatil2510
